-- MySQL Script generated by MySQL Workbench
-- Tue Jan 30 11:00:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BS_BAIKAL
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BS_BAIKAL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BS_BAIKAL` DEFAULT CHARACTER SET utf8mb4 ;
USE `BS_BAIKAL` ;

-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`users` (
  `id_user` CHAR(10) CHARACTER SET 'utf8mb4' NOT NULL,
  `us_lname` VARCHAR(45) NOT NULL,
  `us_fname` VARCHAR(45) NOT NULL,
  `us_otch` VARCHAR(45) NOT NULL,
  `us_dateOfBirth` DATE NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`positions` (
  `id_position` CHAR(10) CHARACTER SET 'utf8mb4' NOT NULL,
  `title_position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_position`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`authorization_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`authorization_users` (
  `id_user` CHAR(10) CHARACTER SET 'utf8mb4' NOT NULL,
  `id_position` CHAR(10) CHARACTER SET 'utf8mb4' NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  INDEX `fk_authorization_users_positions1_idx` (`id_position` ASC) VISIBLE,
  CONSTRAINT `fk_authorization_users_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `BS_BAIKAL`.`users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_authorization_users_positions1`
    FOREIGN KEY (`id_position`)
    REFERENCES `BS_BAIKAL`.`positions` (`id_position`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`pasports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`pasports` (
  `id_passport` INT NOT NULL,
  `title_passport` VARCHAR(45) NOT NULL,
  `fail` BLOB NULL,
  PRIMARY KEY (`id_passport`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`labels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`labels` (
  `id_label` INT NOT NULL,
  `title_label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_label`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`titleGP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`titleGP` (
  `id_titleGP` INT NOT NULL,
  `titleGP` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_titleGP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`container`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`container` (
  `id_container` INT NOT NULL,
  `title_container` VARCHAR(45) NULL,
  PRIMARY KEY (`id_container`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`location` (
  `id_location` INT NOT NULL,
  `title_location` VARCHAR(45) NULL,
  PRIMARY KEY (`id_location`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`status` (
  `id_status` INT NOT NULL,
  `title_status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`orders` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `customer` VARCHAR(45) NOT NULL,
  `data_order_formation` DATE NOT NULL,
  `end_date_agreement` DATE NOT NULL,
  `id_label` INT NOT NULL,
  `id_titleGP` INT NOT NULL,
  `id_container` INT NOT NULL,
  `id_location` INT NOT NULL,
  `id_status` INT NULL,
  `cost` INT NOT NULL,
  `end_date_actually` DATE NULL,
  PRIMARY KEY (`id_order`),
  INDEX `fk_id_label_idx` (`id_label` ASC) VISIBLE,
  INDEX `fk_id_titleGP_idx` (`id_titleGP` ASC) VISIBLE,
  INDEX `fk_id_container_idx` (`id_container` ASC) VISIBLE,
  INDEX `fk_id_location_idx` (`id_location` ASC) VISIBLE,
  INDEX `fk_id_status_idx` (`id_status` ASC) VISIBLE,
  CONSTRAINT `fk_id_label`
    FOREIGN KEY (`id_label`)
    REFERENCES `BS_BAIKAL`.`labels` (`id_label`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_titleGP`
    FOREIGN KEY (`id_titleGP`)
    REFERENCES `BS_BAIKAL`.`titleGP` (`id_titleGP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_container`
    FOREIGN KEY (`id_container`)
    REFERENCES `BS_BAIKAL`.`container` (`id_container`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_location`
    FOREIGN KEY (`id_location`)
    REFERENCES `BS_BAIKAL`.`location` (`id_location`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_status`
    FOREIGN KEY (`id_status`)
    REFERENCES `BS_BAIKAL`.`status` (`id_status`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`productBatchEOK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`productBatchEOK` (
  `id_productBatchEOK` INT NOT NULL AUTO_INCREMENT,
  `begin_production_date` DATE NOT NULL,
  `end_production_date` DATE NULL,
  `acid_number` VARCHAR(45) NULL,
  `comment` VARCHAR(300) NULL,
  PRIMARY KEY (`id_productBatchEOK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`productBatchEOK_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`productBatchEOK_1` (
  `id_productBatchEOK_1` INT NOT NULL,
  `id_productBatchGP` INT NOT NULL,
  INDEX `fk_id_productBatchEOK_1_idx` (`id_productBatchEOK_1` ASC) VISIBLE,
  INDEX `fk_id_productBatchGP_EOK_idx` (`id_productBatchGP` ASC) VISIBLE,
  CONSTRAINT `fk_id_productBatchEOK_1_1`
    FOREIGN KEY (`id_productBatchEOK_1`)
    REFERENCES `BS_BAIKAL`.`productBatchEOK` (`id_productBatchEOK`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_productBatchGP_EOK_1`
    FOREIGN KEY (`id_productBatchGP`)
    REFERENCES `BS_BAIKAL`.`productBatchGP` (`id_productBatchGP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`productBatchEOK_2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`productBatchEOK_2` (
  `id_productBatchEOK_2` INT NOT NULL,
  `id_productBatchGP` INT NOT NULL,
  INDEX `fk_id_productBatchEOK_2_idx` (`id_productBatchEOK_2` ASC) VISIBLE,
  INDEX `fk_id_productBatchGP_EOK_idx` (`id_productBatchGP` ASC) VISIBLE,
  CONSTRAINT `fk_id_productBatchEOK_2_2`
    FOREIGN KEY (`id_productBatchEOK_2`)
    REFERENCES `BS_BAIKAL`.`productBatchEOK` (`id_productBatchEOK`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_productBatchGP_EOK_2`
    FOREIGN KEY (`id_productBatchGP`)
    REFERENCES `BS_BAIKAL`.`productBatchGP` (`id_productBatchGP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`productBatchEOK_3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`productBatchEOK_3` (
  `id_productBatchEOK_3` INT NOT NULL,
  `id_productBatchGP` INT NOT NULL,
  INDEX `fk_id_productBatchEOK_3_idx` (`id_productBatchEOK_3` ASC) VISIBLE,
  INDEX `fk_id_productBatchGP_EOK_3_idx` (`id_productBatchGP` ASC) VISIBLE,
  CONSTRAINT `fk_id_productBatchEOK_3_3`
    FOREIGN KEY (`id_productBatchEOK_3`)
    REFERENCES `BS_BAIKAL`.`productBatchEOK` (`id_productBatchEOK`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_productBatchGP_EOK_3`
    FOREIGN KEY (`id_productBatchGP`)
    REFERENCES `BS_BAIKAL`.`productBatchGP` (`id_productBatchGP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`productBatchPAYAK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`productBatchPAYAK` (
  `id_productBatchPAYAK` INT NOT NULL AUTO_INCREMENT,
  `begin_production_date` DATE NOT NULL,
  `end_production_date` DATE NULL,
  `acid_number` VARCHAR(45) NULL,
  `comment` VARCHAR(300) NULL,
  PRIMARY KEY (`id_productBatchPAYAK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`productBatchPAYAK_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`productBatchPAYAK_1` (
  `id_productBatchPAYAK_1` INT NOT NULL,
  `id_productBatchGP` INT NOT NULL,
  INDEX `fk_id_productBatchPAYAK_1_idx` (`id_productBatchPAYAK_1` ASC) VISIBLE,
  INDEX `fk_id_productBatchGP_PYAYK_1_idx` (`id_productBatchGP` ASC) VISIBLE,
  CONSTRAINT `fk_id_productBatchPAYAK_1_1`
    FOREIGN KEY (`id_productBatchPAYAK_1`)
    REFERENCES `BS_BAIKAL`.`productBatchPAYAK` (`id_productBatchPAYAK`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_productBatchGP_PAYAK_1`
    FOREIGN KEY (`id_productBatchGP`)
    REFERENCES `BS_BAIKAL`.`productBatchGP` (`id_productBatchGP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`productBatchPAYAK_2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`productBatchPAYAK_2` (
  `id_productBatchPAYAK_2` INT NOT NULL,
  `id_productBatchGP` INT NOT NULL,
  INDEX `fk_id_productBatchPAYAK_2_idx` (`id_productBatchPAYAK_2` ASC) VISIBLE,
  INDEX `fk_id_productBatchGP_PAYAK_2_idx` (`id_productBatchGP` ASC) VISIBLE,
  CONSTRAINT `fk_id_productBatchPAYAK_2_2`
    FOREIGN KEY (`id_productBatchPAYAK_2`)
    REFERENCES `BS_BAIKAL`.`productBatchPAYAK` (`id_productBatchPAYAK`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_productBatchGP_PAYAK_2`
    FOREIGN KEY (`id_productBatchGP`)
    REFERENCES `BS_BAIKAL`.`productBatchGP` (`id_productBatchGP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`productBatchGP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`productBatchGP` (
  `id_productBatchGP` INT NOT NULL AUTO_INCREMENT,
  `id_titleGP` INT NOT NULL,
  `begin_production_date` DATE NOT NULL,
  `end_production_date` VARCHAR(45) NULL,
  `viscosity` VARCHAR(45) NULL,
  `electrical_capacity` VARCHAR(45) NULL,
  `id_productBatchEOK_1` INT NULL,
  `id_productBatchEOK_2` INT NULL,
  `id_productBatchEOK_3` INT NULL,
  `id_productBatchPAYAK_1` INT NULL,
  `id_productBatchPAYAK_2` INT NULL,
  PRIMARY KEY (`id_productBatchGP`),
  INDEX `fk_id_titleGP_idx` (`id_titleGP` ASC) VISIBLE,
  INDEX `fk_id_productBatchEOK_1_idx` (`id_productBatchEOK_1` ASC) VISIBLE,
  INDEX `fk_id_productBatchEOK_2_idx` (`id_productBatchEOK_2` ASC) VISIBLE,
  INDEX `fk_id_productBatchEOK_3_idx` (`id_productBatchEOK_3` ASC) VISIBLE,
  INDEX `fk_id_productBatchPAYAK_1_idx` (`id_productBatchPAYAK_1` ASC) VISIBLE,
  INDEX `fk_id_productBatchPAYAK_2_idx` (`id_productBatchPAYAK_2` ASC) VISIBLE,
  CONSTRAINT `fk_id_titleGP1`
    FOREIGN KEY (`id_titleGP`)
    REFERENCES `BS_BAIKAL`.`titleGP` (`id_titleGP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_productBatchEOK_1`
    FOREIGN KEY (`id_productBatchEOK_1`)
    REFERENCES `BS_BAIKAL`.`productBatchEOK_1` (`id_productBatchEOK_1`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_productBatchEOK_2`
    FOREIGN KEY (`id_productBatchEOK_2`)
    REFERENCES `BS_BAIKAL`.`productBatchEOK_2` (`id_productBatchEOK_2`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_productBatchEOK_3`
    FOREIGN KEY (`id_productBatchEOK_3`)
    REFERENCES `BS_BAIKAL`.`productBatchEOK_3` (`id_productBatchEOK_3`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_productBatchPAYAK_1`
    FOREIGN KEY (`id_productBatchPAYAK_1`)
    REFERENCES `BS_BAIKAL`.`productBatchPAYAK_1` (`id_productBatchPAYAK_1`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_productBatchPAYAK_2`
    FOREIGN KEY (`id_productBatchPAYAK_2`)
    REFERENCES `BS_BAIKAL`.`productBatchPAYAK_2` (`id_productBatchPAYAK_2`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`productBatchGP_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`productBatchGP_1` (
  `id_productBatchGP_1` INT NOT NULL,
  `id_order` INT NOT NULL,
  INDEX `fk_id_productBatchGP_idx` (`id_productBatchGP_1` ASC) VISIBLE,
  INDEX `fk_id_order1_idx` (`id_order` ASC) VISIBLE,
  CONSTRAINT `fk_id_productBatchGP_1_1`
    FOREIGN KEY (`id_productBatchGP_1`)
    REFERENCES `BS_BAIKAL`.`productBatchGP` (`id_productBatchGP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_order1`
    FOREIGN KEY (`id_order`)
    REFERENCES `BS_BAIKAL`.`compositionOrder` (`id_order`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`productBatchGP_2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`productBatchGP_2` (
  `id_productBatchGP_2` INT NOT NULL,
  `id_order` INT NOT NULL,
  INDEX `fk_id_productBatchGP_2_idx` (`id_productBatchGP_2` ASC) VISIBLE,
  INDEX `fk_id_order2_idx` (`id_order` ASC) VISIBLE,
  CONSTRAINT `fk_id_productBatchGP_2_2`
    FOREIGN KEY (`id_productBatchGP_2`)
    REFERENCES `BS_BAIKAL`.`productBatchGP` (`id_productBatchGP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_order2`
    FOREIGN KEY (`id_order`)
    REFERENCES `BS_BAIKAL`.`compositionOrder` (`id_order`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`productBatchGP_3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`productBatchGP_3` (
  `id_productBatchGP_3` INT NOT NULL,
  `id_order` INT NOT NULL,
  INDEX `fk_id_productBatchGP_3_idx` (`id_productBatchGP_3` ASC) VISIBLE,
  INDEX `fk_id_order3_idx` (`id_order` ASC) VISIBLE,
  CONSTRAINT `fk_id_productBatchGP_3_3`
    FOREIGN KEY (`id_productBatchGP_3`)
    REFERENCES `BS_BAIKAL`.`productBatchGP` (`id_productBatchGP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_order3`
    FOREIGN KEY (`id_order`)
    REFERENCES `BS_BAIKAL`.`compositionOrder` (`id_order`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BS_BAIKAL`.`compositionOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BS_BAIKAL`.`compositionOrder` (
  `id_order` INT NOT NULL,
  `composition_order` VARCHAR(400) NOT NULL,
  `fail` BLOB NOT NULL,
  `id_passport` INT NULL,
  `id_productBatchGP_1` INT NULL,
  `id_productBatchGP_2` INT NULL,
  `id_productBatchGP_3` INT NULL,
  INDEX `fk_id_order_idx` (`id_order` ASC) VISIBLE,
  INDEX `fk_id_passpor_idx` (`id_passport` ASC) VISIBLE,
  INDEX `fk_id_productBatchGP_1_idx` (`id_productBatchGP_1` ASC) VISIBLE,
  INDEX `fk_id_productBatchGP_2_idx` (`id_productBatchGP_2` ASC) VISIBLE,
  INDEX `fk_id_productBatchGP_3_idx` (`id_productBatchGP_3` ASC) VISIBLE,
  CONSTRAINT `fk_id_order_1`
    FOREIGN KEY (`id_order`)
    REFERENCES `BS_BAIKAL`.`orders` (`id_order`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_passpor`
    FOREIGN KEY (`id_passport`)
    REFERENCES `BS_BAIKAL`.`pasports` (`id_passport`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_productBatchGP_1`
    FOREIGN KEY (`id_productBatchGP_1`)
    REFERENCES `BS_BAIKAL`.`productBatchGP_1` (`id_productBatchGP_1`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_productBatchGP_2`
    FOREIGN KEY (`id_productBatchGP_2`)
    REFERENCES `BS_BAIKAL`.`productBatchGP_2` (`id_productBatchGP_2`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_productBatchGP_3`
    FOREIGN KEY (`id_productBatchGP_3`)
    REFERENCES `BS_BAIKAL`.`productBatchGP_3` (`id_productBatchGP_3`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
